configs:
  litellm-config:
    content: |
      model_list:
        - model_name: llama3.2:3b
          litellm_params:
            model: openrouter/meta-llama/llama-3.3-70b-instruct:free
            api_key: os.environ/OPENROUTER_API_KEY

        - model_name: nomic-embed-text
          litellm_params:
            model: openrouter/nomic-ai/nomic-embed-text-v1.5
            api_key: os.environ/OPENROUTER_API_KEY

      general_settings:
        master_key: os.environ/LITELLM_MASTER_KEY

services:
  litellm:
    image: docker.litellm.ai/berriai/litellm:main-stable
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    ports:
      - "4000:4000"
    env_file:
      - .env
    configs:
      - source: litellm-config
        target: /app/config.yaml
